name: MobSF APK Analysis

on:
  push:
    paths:
      - '*.apk'
  workflow_dispatch:

jobs:
  analyze-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and Start MobSF
        run: |
          docker pull opensecurity/mobile-security-framework-mobsf:latest
          docker run -d -p 8000:8000 --name mobsf opensecurity/mobile-security-framework-mobsf:latest
          echo "MobSF đang khởi động, đợi 90 giây..."
          sleep 90

      - name: Get MobSF API Key
        id: get_key
        run: |
          curl -X GET http://localhost:8000/api/v1/apikey/ > mobsf_api_key.txt
          cat mobsf_api_key.txt

      - name: Analyze APK with MobSF
        run: |
          apk_file=$(ls *.apk | head -n 1)
          api_key=$(cat mobsf_api_key.txt | tr -d '"')
          json_resp=$(curl -F "file=@$apk_file" -H "Authorization: $api_key" http://localhost:8000/api/v1/upload/)
          scan_hash=$(echo $json_resp -H "Authorization: $api_key" -H "Content-Type: application/json" \
            -X POST -d "{\"hash\": \"$scan_hash\"}" \
            http://localhost:8000/api/v1/report_json/ > mobsf_result.json

      - name: Upload MobSF Report
        uses: actions/upload-artifact@v3
        with:
          name: mobsf-report
          path: mobsf_result.json
